# -*- coding: utf-8 -*-
"""Week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8Hy4JbyQzYCpIx2ZxmMmlmnHAT_vY3w
"""

# MINI SPORTS ANALYTICS WEB APP
# DATA ENGINEERING WORKFLOW
# Badminton Matches Dataset

import pandas as pd
import numpy as np

# Load Dataset

df = pd.read_excel("badminton_matches_150.xlsx")
print("=" * 60)
print("DATASET LOADED SUCCESSFULLY")

# Explore Dataset
print("\nFirst 5 Rows")
print(df.head())

print("\nLast 5 Rows")
print(df.tail())

print("\nDataset Shape")
print(df.shape)

print("\nColumns")
print(df.columns.tolist())

print("\nDataset Information")
print(df.info())

print("\nStatistical Summary")
print(df.describe())

# Check Missing Values
print("\nMissing Values")
print(df.isnull().sum())

# Fill missing values if any exist
if df["duration_minutes"].isnull().sum() > 0:
    df["duration_minutes"] = df["duration_minutes"].fillna(
        df["duration_minutes"].median()
    )

for col in ["city", "stadium", "tournament", "winner"]:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

print("\nMissing Values After Cleaning")
print(df.isnull().sum())

# Check Duplicate Rows
duplicates = df.duplicated().sum()

print("\nNumber of Duplicate Rows:", duplicates)

if duplicates > 0:
    df = df.drop_duplicates()

print("Dataset Shape After Removing Duplicates:", df.shape)


#  Convert Date Column
df["date"] = pd.to_datetime(df["date"])

print("\nData Types")
print(df.dtypes)


# Check Invalid Scores
invalid_scores = df[
    ~(
        ((df["home_score"] == 2) & (df["away_score"].isin([0, 1])))
        |
        ((df["away_score"] == 2) & (df["home_score"].isin([0, 1])))
    )
]

print("\nInvalid Score Records")
print(invalid_scores)

#  Check Negative Values
print("\nNegative Value Check")

numeric_columns = [
    "home_score",
    "away_score",
    "duration_minutes"
]

for col in numeric_columns:
    negatives = (df[col] < 0).sum()
    print(f"{col}: {negatives}")


#Check Year Range
print("\nYear Range")
print("Minimum Year:", df["year"].min())
print("Maximum Year:", df["year"].max())

# Check Unique Values
print("\nUnique Tournament Names")
print(df["tournament"].unique())

print("\nUnique Stages")
print(df["stage"].unique())

print("\nUnique Cities")
print(df["city"].unique())

print("\nUnique Match Types")
print(df["match_type"].unique())

print("\nUnique Categories")
print(df["category"].unique())

#  Standardize Text
text_columns = [
    "city",
    "stadium",
    "tournament",
    "home_team",
    "away_team",
    "winner"
]

for col in text_columns:
    df[col] = df[col].str.strip()

#Validate Winner
def calculate_winner(row):
    if row["home_score"] > row["away_score"]:
        return row["home_team"]
    else:
        return row["away_team"]

df["expected_winner"] = df.apply(calculate_winner, axis=1)

winner_errors = df[df["winner"] != df["expected_winner"]]

print("\nWinner Validation")
print("Incorrect Winner Records:", len(winner_errors))

if len(winner_errors) > 0:
    df["winner"] = df["expected_winner"]

df.drop(columns=["expected_winner"], inplace=True)

# Validate Match Type
print("\nChecking Match Type")

errors = 0

for index, row in df.iterrows():

    if "Singles" in row["category"]:

        if row["match_type"] != "Singles":
            errors += 1

    else:

        if row["match_type"] != "Doubles":
            errors += 1

print("Incorrect Match Types:", errors)

#  Feature Engineering
df["match_result"] = (
    df["home_score"].astype(str)
    + "-"
    + df["away_score"].astype(str)
)

df["month"] = df["date"].dt.month_name()

df["day"] = df["date"].dt.day_name()


#  Dataset Summary
print("\nFinal Dataset Shape")
print(df.shape)

print("\nFinal Data Types")
print(df.dtypes)

print("\nFirst 5 Rows of Clean Dataset")
print(df.head())

df.to_csv("badminton_matches_clean.csv", index=False)

print("\nClean Dataset Saved Successfully!")
print("File Name: badminton_matches_clean.csv")

print("\nData Engineering Process Completed Successfully!")

from google.colab import drive
drive.mount('/content/drive')